const {Router} = require('express')
const AuthenticatedRoutes = Router()
const fileupload = require('express-fileupload')
const {isLoggedIn,loggedInUser,isLoggedInApi} = require('../Middlewares/Authentication')
const {Index,GetSubcategories,GetPostData,GetSingleArticle,WorkOnArticles,loadSingleBlog,EditArticle,LoadCategoriesBlog,UpdatePostedArticle} = require('../Controller/BlogController.js')
const blogRoutes = Router()

blogRoutes.get('/Articles/User',isLoggedIn,loggedInUser,Index)
.post("/Get/Subategories",isLoggedIn,loggedInUser,GetSubcategories)
.post("/Post-articles",isLoggedIn,loggedInUser,fileupload({createParentPath:true}),GetPostData)
.post("/Get-Single-Article",isLoggedIn,loggedInUser,GetSingleArticle)
.post("/WorkOnArticles",isLoggedIn,loggedInUser,WorkOnArticles)
.get('/Edit-Article/:Slug',isLoggedIn,loggedInUser,EditArticle)
.post("/Update-Post-articles",isLoggedIn,loggedInUser,fileupload({createParentPath:true}),UpdatePostedArticle)
.get("/Category/:Slug",isLoggedIn,loggedInUser,LoadCategoriesBlog)
.get("/blog/:Slug",isLoggedIn,loggedInUser,loadSingleBlog)
module.exports = blogRoutes