const {Router} = require('express')
const AuthenticatedRoutes = Router()
const fileupload = require('express-fileupload')
const {isLoggedIn,loggedInUser,isLoggedInApi} = require('../Middlewares/Authentication')
const {Index,GetSubcategories,GetPostData,GetSingleArticle,GetpostComment,getAllComments,WorkOnComments,MembershipData,createMemberships,WorkOnArticles,loadSingleBlog,BlogArticles,EditArticle,getSubCategory,LoadCategoriesBlog,UpdatePostedArticle} = require('../Controller/BlogController.js')
const blogRoutes = Router()

blogRoutes.get('/Articles/User',isLoggedIn,loggedInUser,Index)
.post("/Get/Subategories",isLoggedIn,loggedInUser,GetSubcategories)
.post("/Post-articles",isLoggedIn,loggedInUser,fileupload({createParentPath:true}),GetPostData)
.post("/Get-Single-Article",isLoggedIn,loggedInUser,GetSingleArticle)
.post("/WorkOnArticles",isLoggedIn,loggedInUser,WorkOnArticles)
.get('/Edit-Article/:Slug',isLoggedIn,loggedInUser,EditArticle)
.post("/Update-Post-articles",isLoggedIn,loggedInUser,fileupload({createParentPath:true}),UpdatePostedArticle)
.get("/Category/:Slug",LoadCategoriesBlog)
.get("/blog/:Slug",loadSingleBlog)
.post("/Post-Comment-Blog",GetpostComment)
.get("/subcategory/:Slug",getSubCategory)
.get("/Blog",BlogArticles)
.get("/Admin/Comments",isLoggedIn,loggedInUser,getAllComments)
.post("/WorkOnComments",isLoggedIn,loggedInUser,WorkOnComments)
.get("/Memberships",isLoggedIn,loggedInUser,createMemberships)
.post("/Membership/Post",isLoggedIn,loggedInUser,MembershipData)
module.exports = blogRoutes