const {Router} = require('express')
const {Home,About,Contact,Login,Logout,Reset,Register,Passwords,Register_user,Login_User} = require('../Controller/HomeController.js')
const isGuest = require('../Middlewares/Guest.js')
const homeRouter = Router()

homeRouter.get('/',isGuest,Home)
.get('/About',isGuest,About)
.get('/Logout',Logout)
.get('/Contact',isGuest,Contact)
.get('/Login',isGuest,Login)
.get('/Register',isGuest,Register)
.get('/Reset',isGuest,Reset)
.get('/UpdatePassword',isGuest,Passwords)
.post("/user-Register",Register_user)
.post("/login-user",Login_User)
module.exports = homeRouter