const {Router} = require('express')
const {Home,About,Contact,Login,Logout,Reset,Register,Passwords,Register_user,Login_User} = require('../Controller/HomeController.js')
const isGuest = require('../Middlewares/Guest.js')
const homeRouter = Router()

homeRouter.get('/',Home)
.get('/About',About)
.get('/Logout',Logout)
.get('/Contact',Contact)
.get('/Login',Login)
.get('/Register',Register)
.get('/Reset',Reset)
.get('/UpdatePassword',Passwords)
.post("/user-Register",Register_user)
.post("/login-user",Login_User)
module.exports = homeRouter